In [0]:
from pyspark import storagelevel
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *

In [0]:
# spark.sql("show databases").show()

In [0]:
# Using a previous database
spark.sql("use salesmanagement")

In [0]:
# Show the database tables
spark.sql("show tables").show()

In [0]:
# Seeing the items in the selected table
spark.sql("SELECT * FROM customers").show()

In [0]:
churn = spark.read.format("csv").option("header", True ).load("/learn/Churn")
churn.show()

In [0]:
# Write the data as a partition
churn.write.partitionBy("Geography").saveAsTable("churn_location")

In [0]:
# checking the table
spark.sql(" SELECT * FROM churn_location ").show(10)

In [0]:
# Using the bucket by function
churn.write.bucketBy(2 , "Geography").saveAsTable("churn_location_bucket")
# checking the table
spark.sql(" SELECT * FROM churn_location_bucket ").show(10)